# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from adapters.genproto import monNlpService_pb2 as adapters_dot_genproto_dot_monNlpService__pb2


class MonNlpServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.tokenize = channel.unary_unary(
                '/monNlp.MonNlpService/tokenize',
                request_serializer=adapters_dot_genproto_dot_monNlpService__pb2.TokenizeRequest.SerializeToString,
                response_deserializer=adapters_dot_genproto_dot_monNlpService__pb2.TokenizeResponse.FromString,
                )


class MonNlpServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def tokenize(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MonNlpServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'tokenize': grpc.unary_unary_rpc_method_handler(
                    servicer.tokenize,
                    request_deserializer=adapters_dot_genproto_dot_monNlpService__pb2.TokenizeRequest.FromString,
                    response_serializer=adapters_dot_genproto_dot_monNlpService__pb2.TokenizeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'monNlp.MonNlpService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MonNlpService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def tokenize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/monNlp.MonNlpService/tokenize',
            adapters_dot_genproto_dot_monNlpService__pb2.TokenizeRequest.SerializeToString,
            adapters_dot_genproto_dot_monNlpService__pb2.TokenizeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
